# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_type', models.CharField(blank=True, choices=[('Nikon', 'Nikon'), ('iPhone', 'iPhone'), ('Canon', 'Canon'), ('--------', '--------')], default='--------', max_length=10)),
                ('address', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('bio', models.TextField(default='')),
                ('personal_website', models.URLField(default='')),
                ('for_hire', models.BooleanField(default=False)),
                ('travel_distance', models.IntegerField(blank=True, default=0)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('photography_type', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
