# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='imagerprofile',
            name='camera_type',
            field=models.CharField(blank=True, choices=[('Nikon', 'Nikon'), ('iPhone', 'iPhone'), ('Canon', 'Canon')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='imagerprofile',
            name='for_hire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagerprofile',
            name='personal_website',
            field=models.URLField(default=''),
        ),
    ]
