# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20170117_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='photography_type',
            field=models.CharField(blank=True, choices=[('nature', 'nature'), ('urban', 'urban'), ('portraits', 'portraits')], max_length=20, null=True),
        ),
    ]
