# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_auto_20170119_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
