language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install:
  # - pip install .
  - pip install -r requirements.pip

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
    secure: "c3J0p4fxJkSRfcwkYRmsRcjkgcwnZsIk9ODOwp0061iOHMSMdgzwbxBKWloSboBHuqpH+3qR+BsmW0CiuZo2sFnifT8NTMnllhNyVOSVTVflCMHZ/rkk5VYkEsBr+ao9r1k47OZKsq6297m116ou2iOGIJVokCpRHh0cOBY28FNSt6+x9lXksfdQKS8JT8DchO7ZCbYdv3FEPGhnnyQ8bpWV9VCdBcCoXOLQfYdXXyptUwbbW9sxCyHbTKgaPl85uBchFAG6H0l9kM2jOrFfXPgCTik5pJiznS2pLbTgq+p3WhqAJcU1kBeJcZJ+TGod3kvM3mHGRklMs8evKl7edcfVHCtGMGt9vuP6uOPM+JlY2m3ANkfM2wpTz3HgO/pxg1vG0HMqywhm6Q7rxhoBZAFqGdB/oePrDesBR7JRsVis1kE5nT9Lp/9XFiLhJ0K8p1hHZW2MW3HQs10JQwqDLNCkeA9rBnOaRy2chQ2uXkOJeT6E22cD4ktYHse6ay6XWQX9VA8oiYNc4eadCT7dbdaev7J2iesNCP9FOx7We4zVtDa5gzP1p++zhiP9yFz++3Dl47HTAZrxAxtyFI4zH0l/UuCws3Z66SxjFTEs5PcwC6uIktSeGjXvabMSHZmi1KDh9zg9bXjCzf/KZXZ2OprkFgUqWjoPtP7VZ50YQ6g="

# command to run tests
script: python imagersite/manage.py test

notifications:
  email: false