language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install:
  # - pip install .
  - pip install -r requirements.pip

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to run tests
script: python imagersite/manage.py test